### ISSUE TITLE
Including `haproxy::app_lb` in run list doesn't write proper haproxy.cfg

### ISSUE THREAD

**Issue by ianrossi** [sous-chefs/haproxy#109]
@slyness This is an issue only in `master`. In `develop`, I'm able to put `haproxy::app_lb` in my run list with the following role and `/etc/haproxy.cfg` is written properly. If I do this same thing with the `master` branch of this cookbook, `/etc/haproxy.cfg` remains unchanged as the default file installed with the `haproxy` package. This is on Centos 6.5. Can I help out?

p.s. Whazzup?!

```
name 'haproxy_lb'
default_attributes(
  :haproxy => {
    :app_server_role => 'fit_api_server',
    :enable_default_http => false
  }
)
run_list 'recipe[haproxy::app_lb]'
```

**Comment by alxndrmlr** [comment]
@ianrossi were you able to resolve this. I'm running into this as well.

**Comment by ianrossi** [comment]
@alxndrmlr I worked around this by using the `develop` branch. I'm using `librarian-chef` for cookbook dependency management, so I put the following in my `Cheffile`:
```
cookbook 'haproxy', :git => 'git@github.com:hw-cookbooks/haproxy.git', :ref => 'develop'
```
Then, I install all cookbooks in the Cheffile by doing:
```
librarian-chef install
```
Then I upload the `haproxy` cookbook to my Chef Server.

Hope that helps.

**Comment by mlavi** [comment]
I have also encountered this on CentOS 6.5 on master. :~(

**Comment by alxndrmlr** [comment]
Got it working off the dev branch as well.

**Comment by khalaan** [comment]
I am working with organizations that need to pull from supermarket, pulling from branches via GIT isn't a viable solution. Is there anyway the haproxy_config LWRP can be merged into master?

**Comment by elijah** [comment]
This does indeed deserve to be merged and version bumped... please.

**Comment by ianrossi** [comment]
@elijah Are you asking for the `develop` branch to be merged to `master`?

**Comment by elijah** [comment]
It would certainly save me from a bunch of extra work hacking together a
sketchy version-bumped copy to upload to a very large organization's
supermarket.  :-)  [I'm not altogether certain that merely telling
Berkshelf to pull from the develop branch on github will work -- some
limitations on what I can force people to allow our pipeline to do.]

It would be appreciated :)

I found a few other weird things this afternoon, too - using an EPEL copy
of haproxy on fairly old AMI.  Had to create user and group for haproxy by
hand in my recipe, because the RPM failed to do so...  was going to PR that
and a few other things this evening, if I get a few moments.

--e

**Comment by tas50** [comment]
Develop branch will go away soon

**Comment by ianrossi** [comment]
I didn't do a diff or anything but this a branch I had working that fixed a problem with the source install. I think this might have been merged, though. But has been working for me in production.
https://github.com/aimtheory/haproxy/tree/fix/install_source

**Comment by rshade** [comment]
@ianrossi can you see if this works on the latest version?

**Comment by damacus** [comment]
@ianrossi I'm going to close this issue now as we've significantly changed the way to cookbook configures things. 
We'll not be doing any patches to v3.

If v4 does not work in some way please open a ticket. 

Thanks!
