### ISSUE TITLE
I would like to protect master, and also set squash merge only. 

### ISSUE THREAD

**Issue by rshade** [sous-chefs/haproxy#149]
I would like to protect the master branch, and then set the merge rule to "squash merge" only. What are your thoughts on this?

**Comment by tas50** [comment]
I'm all for turning on protected branches on master. I'm not a fan of squash merges though. You lose the history of where the commit actually came from. I know a lot of people like them for the straight up down history they provide visually, but you're getting that because you're losing information.

**Comment by tas50** [comment]
Protected branch with required Travis pass and forced reviews are enabled now

**Comment by tas50** [comment]
If you think you're doing too much you can squash a bit. I think it's useful to see the progression. I hit git history a lot to try to figure out why particular lines where changes and it's really hard when you see something like "drop this giant 500 line feature commit".

**Comment by damacus** [comment]
From Slack

- Protected Master
- At least one review from another party
- We should fix the build if the tests are red.
- Squash Merging is OK on a per repo basis. 
The idea here, is to get clean understandable updates, and good git history.
Rather than hiding a mess under the carpet.
